spring:
  application:
    name: micro
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  mvc:
    contentnegotiation:
      favor-parameter: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

rankpointable:
  punteggiopresenza: 2
  battle:
    ottavi: 2
    quarti: 4
    semifinale: 8
    finale : 12
  moltiplicatore:
    casa: 1
    regionale: 1.5

